language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis flake8
script:
- flake8 .
- tox
after_success:
- bash <(curl -s https://codecov.io/bash) -t 598bb588-3343-49c1-a555-112cdbfae9d3